from __future__ import annotations

import subprocess
import tempfile
from io import BytesIO
from pathlib import Path


def pdf_bytes(text: str) -> bytes:
    escaped_lines = []
    for line in text.splitlines() or [""]:
        escaped = (
            line.replace("\\", "\\\\")
            .replace("(", "\\(")
            .replace(")", "\\)")
        )
        escaped_lines.append(escaped)
    commands = ["BT", "/F1 11 Tf", "72 720 Td"]
    for index, line in enumerate(escaped_lines):
        if index:
            commands.append("0 -14 Td")
        commands.append(f"({line}) Tj")
    commands.append("ET")
    stream = "\n".join(commands).encode("latin-1", errors="replace")
    objects = [
        b"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n",
        b"2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n",
        (
            b"3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj\n"
        ),
        b"4 0 obj << /Length %d >> stream\n" % len(stream) + stream + b"\nendstream endobj\n",
        b"5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n",
    ]
    header = b"%PDF-1.4\n"
    body = header
    offsets = [0]
    for obj in objects:
        offsets.append(len(body))
        body += obj
    xref_pos = len(body)
    xref = [b"xref\n0 6\n0000000000 65535 f \n"]
    for offset in offsets[1:]:
        xref.append(f"{offset:010d} 00000 n \n".encode("ascii"))
    trailer = (
        b"".join(xref)
        + b"trailer << /Size 6 /Root 1 0 R >>\nstartxref\n"
        + str(xref_pos).encode("ascii")
        + b"\n%%EOF\n"
    )
    return body + trailer


def docx_bytes(text: str) -> bytes:
    from docx import Document

    document = Document()
    for line in text.splitlines():
        document.add_paragraph(line)
    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def odt_bytes(text: str) -> bytes:
    from odf.opendocument import OpenDocumentText
    from odf.text import P

    document = OpenDocumentText()
    for line in text.splitlines():
        document.text.addElement(P(text=line))
    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def rtf_bytes(text: str) -> bytes:
    parts = [r"{\rtf1\ansi\deff0 {\fonttbl {\f0 Times New Roman;}}\f0\fs24 "]
    for line in text.splitlines():
        escaped = line.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
        parts.append(escaped + r"\par ")
    parts.append("}")
    return "".join(parts).encode("latin-1", errors="replace")


def txt_bytes(text: str) -> bytes:
    return text.encode("utf-8")


def doc_bytes(text: str) -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        source = Path(tmp) / "cv.txt"
        source.write_text(text, encoding="utf-8")
        result = subprocess.run(
            ["textutil", "-convert", "doc", str(source)],
            capture_output=True,
            text=True,
        )
        converted = source.with_suffix(".doc")
        if result.returncode == 0 and converted.exists():
            return converted.read_bytes()
    return _ole_with_ascii(text)


def _ole_with_ascii(text: str) -> bytes:
    import olefile

    payload = text.encode("utf-16le")
    # olefile cannot easily create a new compound file; embed text after a
    # valid OLE header generated by writing a tiny CFB via OleFileIO if possible.
    header = bytearray(512)
    header[0:8] = b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"
    header[0x1E:0x20] = b"\x3e\x00"  # sector size 512
    header[0x20:0x22] = b"\x03\x00"
    # Fallback: magic + padding + utf-16 and ascii copies so the string scraper works
    # if olefile rejects the stub. Tests skip if neither path yields text.
    blob = bytes(header) + b"\x00" * 1024 + payload + b"\n" + text.encode("ascii", errors="ignore")
    try:
        olefile.OleFileIO(BytesIO(blob))
    except Exception:
        pass
    return blob
